using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Security.AccessControl;
using System.Text;
using System.Threading.Tasks;

namespace TnTComponents.Color;
public class TnTTheme {
    public TnTColor Primary = new("#7547ad");
    public TnTColor OnPrimary = new("#ffffff");
    public TnTColor PrimaryContainer = new("#eedbff");
    public TnTColor OnPrimaryContainer = new("#2a0054");
    public TnTColor Secondary = new("#755b00");
    public TnTColor OnSecondary = new("#ffffff");
    public TnTColor SecondaryContainer = new("#ffdf91");
    public TnTColor OnSecondaryContainer = new("#241a00");
    public TnTColor Tertiary = new("#005ac1");
    public TnTColor OnTertiary = new("#ffffff");
    public TnTColor TertiaryContainer = new("#d8e2ff");
    public TnTColor OnTertiaryContainer = new("#001a41");
    public TnTColor Error = new("#ba1a1a");
    public TnTColor ErrorContainer = new("#ffdad6");
    public TnTColor OnError = new("#ffffff");
    public TnTColor OnErrorContainer = new("#410002");
    public TnTColor Background = new("#fef7ff");
    public TnTColor OnBackground = new("#1d1b20");
    public TnTColor Surface = new("#fef7ff");
    public TnTColor OnSurface = new("#1d1b20");
    public TnTColor SurfaceVariant = new("#e8e0eb");
    public TnTColor OnSurfaceVariant = new("#49454f");
    public TnTColor SurfaceContainerHighest = new("#e7e1e5");
    public TnTColor SurfaceContainerHigh = new("#ece6f0");
    public TnTColor SurfaceContainer = new("#f3edf7");
    public TnTColor SurfaceContainerLow = new("#f7f2fa");
    public TnTColor SurfaceContainerLowest = new("#ffffff");
    public TnTColor Outline = new("#7b757f");
    public TnTColor InverseOnSurface = new("#f5eff4");
    public TnTColor InverseSurface = new("#322f33");
    public TnTColor InversePrimary = new("#d9b9ff");
    public TnTColor Shadow = new("#565656");
    public TnTColor SurfaceTint = new("#7547ad");
    public TnTColor OutlineVariant = new("#ccc4cf");
    public TnTColor Scrim = new("#000000");
    public TnTColor Warning = new("#845400");
    public TnTColor OnWarning = new("#ffffff");
    public TnTColor WarningContainer = new("#ffddb6");
    public TnTColor OnWarningContainer = new("#2a1800");
    public TnTColor Success = new("#006c4c");
    public TnTColor OnSuccess = new("#ffffff");
    public TnTColor SuccessContainer = new("#54febf");
    public TnTColor OnSuccessContainer = new("#002115");
    public TnTColor Info = new("#0d60a8");
    public TnTColor OnInfo = new("#ffffff");
    public TnTColor InfoContainer = new("#d3e3ff");
    public TnTColor OnInfoContainer = new("#001c39");
}

